# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from psdomain.proto.orderstatus import orderstatus_pb2 as proto_dot_orderstatus_dot_orderstatus__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/orderstatus/orderstatus_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrderStatusServiceStub(object):
    """OrderStatusService provides methods for Order Status data (v1.0.0 and v2.0.0)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOrderStatusDetails = channel.unary_unary(
                '/orderstatus.OrderStatusService/GetOrderStatusDetails',
                request_serializer=proto_dot_orderstatus_dot_orderstatus__pb2.GetOrderStatusDetailsRequest.SerializeToString,
                response_deserializer=proto_dot_orderstatus_dot_orderstatus__pb2.GetOrderStatusDetailsResponse.FromString,
                _registered_method=True)
        self.GetOrderStatusTypes = channel.unary_unary(
                '/orderstatus.OrderStatusService/GetOrderStatusTypes',
                request_serializer=proto_dot_orderstatus_dot_orderstatus__pb2.GetOrderStatusTypesRequest.SerializeToString,
                response_deserializer=proto_dot_orderstatus_dot_orderstatus__pb2.GetOrderStatusTypesResponse.FromString,
                _registered_method=True)
        self.GetOrderStatus = channel.unary_unary(
                '/orderstatus.OrderStatusService/GetOrderStatus',
                request_serializer=proto_dot_orderstatus_dot_orderstatus__pb2.GetOrderStatusRequest.SerializeToString,
                response_deserializer=proto_dot_orderstatus_dot_orderstatus__pb2.GetOrderStatusResponse.FromString,
                _registered_method=True)
        self.GetIssue = channel.unary_unary(
                '/orderstatus.OrderStatusService/GetIssue',
                request_serializer=proto_dot_orderstatus_dot_orderstatus__pb2.GetIssueRequest.SerializeToString,
                response_deserializer=proto_dot_orderstatus_dot_orderstatus__pb2.GetIssueResponse.FromString,
                _registered_method=True)
        self.GetServiceMethods = channel.unary_unary(
                '/orderstatus.OrderStatusService/GetServiceMethods',
                request_serializer=proto_dot_orderstatus_dot_orderstatus__pb2.GetServiceMethodsRequest.SerializeToString,
                response_deserializer=proto_dot_orderstatus_dot_orderstatus__pb2.GetServiceMethodsResponse.FromString,
                _registered_method=True)


class OrderStatusServiceServicer(object):
    """OrderStatusService provides methods for Order Status data (v1.0.0 and v2.0.0)
    """

    def GetOrderStatusDetails(self, request, context):
        """v1.0.0 Methods
        GetOrderStatusDetails retrieves order status details based on query type
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderStatusTypes(self, request, context):
        """GetOrderStatusTypes retrieves the list of supported order status types
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderStatus(self, request, context):
        """v2.0.0 Methods
        GetOrderStatus retrieves order status (v2.0.0 - more options than v1)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIssue(self, request, context):
        """GetIssue retrieves issue details by issue ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceMethods(self, request, context):
        """GetServiceMethods retrieves the list of supported service methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderStatusServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOrderStatusDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderStatusDetails,
                    request_deserializer=proto_dot_orderstatus_dot_orderstatus__pb2.GetOrderStatusDetailsRequest.FromString,
                    response_serializer=proto_dot_orderstatus_dot_orderstatus__pb2.GetOrderStatusDetailsResponse.SerializeToString,
            ),
            'GetOrderStatusTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderStatusTypes,
                    request_deserializer=proto_dot_orderstatus_dot_orderstatus__pb2.GetOrderStatusTypesRequest.FromString,
                    response_serializer=proto_dot_orderstatus_dot_orderstatus__pb2.GetOrderStatusTypesResponse.SerializeToString,
            ),
            'GetOrderStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderStatus,
                    request_deserializer=proto_dot_orderstatus_dot_orderstatus__pb2.GetOrderStatusRequest.FromString,
                    response_serializer=proto_dot_orderstatus_dot_orderstatus__pb2.GetOrderStatusResponse.SerializeToString,
            ),
            'GetIssue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIssue,
                    request_deserializer=proto_dot_orderstatus_dot_orderstatus__pb2.GetIssueRequest.FromString,
                    response_serializer=proto_dot_orderstatus_dot_orderstatus__pb2.GetIssueResponse.SerializeToString,
            ),
            'GetServiceMethods': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceMethods,
                    request_deserializer=proto_dot_orderstatus_dot_orderstatus__pb2.GetServiceMethodsRequest.FromString,
                    response_serializer=proto_dot_orderstatus_dot_orderstatus__pb2.GetServiceMethodsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orderstatus.OrderStatusService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orderstatus.OrderStatusService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderStatusService(object):
    """OrderStatusService provides methods for Order Status data (v1.0.0 and v2.0.0)
    """

    @staticmethod
    def GetOrderStatusDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orderstatus.OrderStatusService/GetOrderStatusDetails',
            proto_dot_orderstatus_dot_orderstatus__pb2.GetOrderStatusDetailsRequest.SerializeToString,
            proto_dot_orderstatus_dot_orderstatus__pb2.GetOrderStatusDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrderStatusTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orderstatus.OrderStatusService/GetOrderStatusTypes',
            proto_dot_orderstatus_dot_orderstatus__pb2.GetOrderStatusTypesRequest.SerializeToString,
            proto_dot_orderstatus_dot_orderstatus__pb2.GetOrderStatusTypesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrderStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orderstatus.OrderStatusService/GetOrderStatus',
            proto_dot_orderstatus_dot_orderstatus__pb2.GetOrderStatusRequest.SerializeToString,
            proto_dot_orderstatus_dot_orderstatus__pb2.GetOrderStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIssue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orderstatus.OrderStatusService/GetIssue',
            proto_dot_orderstatus_dot_orderstatus__pb2.GetIssueRequest.SerializeToString,
            proto_dot_orderstatus_dot_orderstatus__pb2.GetIssueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServiceMethods(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orderstatus.OrderStatusService/GetServiceMethods',
            proto_dot_orderstatus_dot_orderstatus__pb2.GetServiceMethodsRequest.SerializeToString,
            proto_dot_orderstatus_dot_orderstatus__pb2.GetServiceMethodsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
