# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from psdomain.proto.companydata import companydata_pb2 as proto_dot_companydata_dot_companydata__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/companydata/companydata_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CompanyDataServiceStub(object):
    """Company Data Service v1.0.0
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCompanyData = channel.unary_unary(
                '/companydata.CompanyDataService/GetCompanyData',
                request_serializer=proto_dot_companydata_dot_companydata__pb2.GetCompanyDataRequest.SerializeToString,
                response_deserializer=proto_dot_companydata_dot_companydata__pb2.GetCompanyDataResponse.FromString,
                _registered_method=True)
        self.GetAvailablePromoStandardsServices = channel.unary_unary(
                '/companydata.CompanyDataService/GetAvailablePromoStandardsServices',
                request_serializer=proto_dot_companydata_dot_companydata__pb2.GetAvailablePromoStandardsServicesRequest.SerializeToString,
                response_deserializer=proto_dot_companydata_dot_companydata__pb2.GetAvailablePromoStandardsServicesResponse.FromString,
                _registered_method=True)
        self.GetPromoStandardsServiceDetails = channel.unary_unary(
                '/companydata.CompanyDataService/GetPromoStandardsServiceDetails',
                request_serializer=proto_dot_companydata_dot_companydata__pb2.GetPromoStandardsServiceDetailsRequest.SerializeToString,
                response_deserializer=proto_dot_companydata_dot_companydata__pb2.GetPromoStandardsServiceDetailsResponse.FromString,
                _registered_method=True)
        self.GetBusinessCharacteristics = channel.unary_unary(
                '/companydata.CompanyDataService/GetBusinessCharacteristics',
                request_serializer=proto_dot_companydata_dot_companydata__pb2.GetBusinessCharacteristicsRequest.SerializeToString,
                response_deserializer=proto_dot_companydata_dot_companydata__pb2.GetBusinessCharacteristicsResponse.FromString,
                _registered_method=True)
        self.GetCertifications = channel.unary_unary(
                '/companydata.CompanyDataService/GetCertifications',
                request_serializer=proto_dot_companydata_dot_companydata__pb2.GetCertificationsRequest.SerializeToString,
                response_deserializer=proto_dot_companydata_dot_companydata__pb2.GetCertificationsResponse.FromString,
                _registered_method=True)
        self.GetContacts = channel.unary_unary(
                '/companydata.CompanyDataService/GetContacts',
                request_serializer=proto_dot_companydata_dot_companydata__pb2.GetContactsRequest.SerializeToString,
                response_deserializer=proto_dot_companydata_dot_companydata__pb2.GetContactsResponse.FromString,
                _registered_method=True)
        self.GetPaymentMethods = channel.unary_unary(
                '/companydata.CompanyDataService/GetPaymentMethods',
                request_serializer=proto_dot_companydata_dot_companydata__pb2.GetPaymentMethodsRequest.SerializeToString,
                response_deserializer=proto_dot_companydata_dot_companydata__pb2.GetPaymentMethodsResponse.FromString,
                _registered_method=True)
        self.GetPaymentTerms = channel.unary_unary(
                '/companydata.CompanyDataService/GetPaymentTerms',
                request_serializer=proto_dot_companydata_dot_companydata__pb2.GetPaymentTermsRequest.SerializeToString,
                response_deserializer=proto_dot_companydata_dot_companydata__pb2.GetPaymentTermsResponse.FromString,
                _registered_method=True)
        self.GetPhysicalLocations = channel.unary_unary(
                '/companydata.CompanyDataService/GetPhysicalLocations',
                request_serializer=proto_dot_companydata_dot_companydata__pb2.GetPhysicalLocationsRequest.SerializeToString,
                response_deserializer=proto_dot_companydata_dot_companydata__pb2.GetPhysicalLocationsResponse.FromString,
                _registered_method=True)
        self.GetPolicies = channel.unary_unary(
                '/companydata.CompanyDataService/GetPolicies',
                request_serializer=proto_dot_companydata_dot_companydata__pb2.GetPoliciesRequest.SerializeToString,
                response_deserializer=proto_dot_companydata_dot_companydata__pb2.GetPoliciesResponse.FromString,
                _registered_method=True)
        self.GetShippingMethods = channel.unary_unary(
                '/companydata.CompanyDataService/GetShippingMethods',
                request_serializer=proto_dot_companydata_dot_companydata__pb2.GetShippingMethodsRequest.SerializeToString,
                response_deserializer=proto_dot_companydata_dot_companydata__pb2.GetShippingMethodsResponse.FromString,
                _registered_method=True)
        self.GetServiceMethods = channel.unary_unary(
                '/companydata.CompanyDataService/GetServiceMethods',
                request_serializer=proto_dot_companydata_dot_companydata__pb2.GetServiceMethodsRequest.SerializeToString,
                response_deserializer=proto_dot_companydata_dot_companydata__pb2.GetServiceMethodsResponse.FromString,
                _registered_method=True)


class CompanyDataServiceServicer(object):
    """Company Data Service v1.0.0
    """

    def GetCompanyData(self, request, context):
        """Get company data (main/consolidated endpoint)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailablePromoStandardsServices(self, request, context):
        """Get available PromoStandards services
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPromoStandardsServiceDetails(self, request, context):
        """Get PromoStandards service details
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBusinessCharacteristics(self, request, context):
        """Get business characteristics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCertifications(self, request, context):
        """Get certifications
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContacts(self, request, context):
        """Get contacts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPaymentMethods(self, request, context):
        """Get payment methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPaymentTerms(self, request, context):
        """Get payment terms
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPhysicalLocations(self, request, context):
        """Get physical locations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPolicies(self, request, context):
        """Get policies
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShippingMethods(self, request, context):
        """Get shipping methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceMethods(self, request, context):
        """Get service methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CompanyDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCompanyData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCompanyData,
                    request_deserializer=proto_dot_companydata_dot_companydata__pb2.GetCompanyDataRequest.FromString,
                    response_serializer=proto_dot_companydata_dot_companydata__pb2.GetCompanyDataResponse.SerializeToString,
            ),
            'GetAvailablePromoStandardsServices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailablePromoStandardsServices,
                    request_deserializer=proto_dot_companydata_dot_companydata__pb2.GetAvailablePromoStandardsServicesRequest.FromString,
                    response_serializer=proto_dot_companydata_dot_companydata__pb2.GetAvailablePromoStandardsServicesResponse.SerializeToString,
            ),
            'GetPromoStandardsServiceDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPromoStandardsServiceDetails,
                    request_deserializer=proto_dot_companydata_dot_companydata__pb2.GetPromoStandardsServiceDetailsRequest.FromString,
                    response_serializer=proto_dot_companydata_dot_companydata__pb2.GetPromoStandardsServiceDetailsResponse.SerializeToString,
            ),
            'GetBusinessCharacteristics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBusinessCharacteristics,
                    request_deserializer=proto_dot_companydata_dot_companydata__pb2.GetBusinessCharacteristicsRequest.FromString,
                    response_serializer=proto_dot_companydata_dot_companydata__pb2.GetBusinessCharacteristicsResponse.SerializeToString,
            ),
            'GetCertifications': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCertifications,
                    request_deserializer=proto_dot_companydata_dot_companydata__pb2.GetCertificationsRequest.FromString,
                    response_serializer=proto_dot_companydata_dot_companydata__pb2.GetCertificationsResponse.SerializeToString,
            ),
            'GetContacts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContacts,
                    request_deserializer=proto_dot_companydata_dot_companydata__pb2.GetContactsRequest.FromString,
                    response_serializer=proto_dot_companydata_dot_companydata__pb2.GetContactsResponse.SerializeToString,
            ),
            'GetPaymentMethods': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPaymentMethods,
                    request_deserializer=proto_dot_companydata_dot_companydata__pb2.GetPaymentMethodsRequest.FromString,
                    response_serializer=proto_dot_companydata_dot_companydata__pb2.GetPaymentMethodsResponse.SerializeToString,
            ),
            'GetPaymentTerms': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPaymentTerms,
                    request_deserializer=proto_dot_companydata_dot_companydata__pb2.GetPaymentTermsRequest.FromString,
                    response_serializer=proto_dot_companydata_dot_companydata__pb2.GetPaymentTermsResponse.SerializeToString,
            ),
            'GetPhysicalLocations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPhysicalLocations,
                    request_deserializer=proto_dot_companydata_dot_companydata__pb2.GetPhysicalLocationsRequest.FromString,
                    response_serializer=proto_dot_companydata_dot_companydata__pb2.GetPhysicalLocationsResponse.SerializeToString,
            ),
            'GetPolicies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolicies,
                    request_deserializer=proto_dot_companydata_dot_companydata__pb2.GetPoliciesRequest.FromString,
                    response_serializer=proto_dot_companydata_dot_companydata__pb2.GetPoliciesResponse.SerializeToString,
            ),
            'GetShippingMethods': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShippingMethods,
                    request_deserializer=proto_dot_companydata_dot_companydata__pb2.GetShippingMethodsRequest.FromString,
                    response_serializer=proto_dot_companydata_dot_companydata__pb2.GetShippingMethodsResponse.SerializeToString,
            ),
            'GetServiceMethods': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceMethods,
                    request_deserializer=proto_dot_companydata_dot_companydata__pb2.GetServiceMethodsRequest.FromString,
                    response_serializer=proto_dot_companydata_dot_companydata__pb2.GetServiceMethodsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'companydata.CompanyDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('companydata.CompanyDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CompanyDataService(object):
    """Company Data Service v1.0.0
    """

    @staticmethod
    def GetCompanyData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/companydata.CompanyDataService/GetCompanyData',
            proto_dot_companydata_dot_companydata__pb2.GetCompanyDataRequest.SerializeToString,
            proto_dot_companydata_dot_companydata__pb2.GetCompanyDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvailablePromoStandardsServices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/companydata.CompanyDataService/GetAvailablePromoStandardsServices',
            proto_dot_companydata_dot_companydata__pb2.GetAvailablePromoStandardsServicesRequest.SerializeToString,
            proto_dot_companydata_dot_companydata__pb2.GetAvailablePromoStandardsServicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPromoStandardsServiceDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/companydata.CompanyDataService/GetPromoStandardsServiceDetails',
            proto_dot_companydata_dot_companydata__pb2.GetPromoStandardsServiceDetailsRequest.SerializeToString,
            proto_dot_companydata_dot_companydata__pb2.GetPromoStandardsServiceDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBusinessCharacteristics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/companydata.CompanyDataService/GetBusinessCharacteristics',
            proto_dot_companydata_dot_companydata__pb2.GetBusinessCharacteristicsRequest.SerializeToString,
            proto_dot_companydata_dot_companydata__pb2.GetBusinessCharacteristicsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCertifications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/companydata.CompanyDataService/GetCertifications',
            proto_dot_companydata_dot_companydata__pb2.GetCertificationsRequest.SerializeToString,
            proto_dot_companydata_dot_companydata__pb2.GetCertificationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/companydata.CompanyDataService/GetContacts',
            proto_dot_companydata_dot_companydata__pb2.GetContactsRequest.SerializeToString,
            proto_dot_companydata_dot_companydata__pb2.GetContactsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPaymentMethods(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/companydata.CompanyDataService/GetPaymentMethods',
            proto_dot_companydata_dot_companydata__pb2.GetPaymentMethodsRequest.SerializeToString,
            proto_dot_companydata_dot_companydata__pb2.GetPaymentMethodsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPaymentTerms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/companydata.CompanyDataService/GetPaymentTerms',
            proto_dot_companydata_dot_companydata__pb2.GetPaymentTermsRequest.SerializeToString,
            proto_dot_companydata_dot_companydata__pb2.GetPaymentTermsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPhysicalLocations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/companydata.CompanyDataService/GetPhysicalLocations',
            proto_dot_companydata_dot_companydata__pb2.GetPhysicalLocationsRequest.SerializeToString,
            proto_dot_companydata_dot_companydata__pb2.GetPhysicalLocationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPolicies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/companydata.CompanyDataService/GetPolicies',
            proto_dot_companydata_dot_companydata__pb2.GetPoliciesRequest.SerializeToString,
            proto_dot_companydata_dot_companydata__pb2.GetPoliciesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShippingMethods(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/companydata.CompanyDataService/GetShippingMethods',
            proto_dot_companydata_dot_companydata__pb2.GetShippingMethodsRequest.SerializeToString,
            proto_dot_companydata_dot_companydata__pb2.GetShippingMethodsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServiceMethods(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/companydata.CompanyDataService/GetServiceMethods',
            proto_dot_companydata_dot_companydata__pb2.GetServiceMethodsRequest.SerializeToString,
            proto_dot_companydata_dot_companydata__pb2.GetServiceMethodsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
