# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.inventory import v121_pb2 as proto_dot_inventory_dot_v121__pb2
from proto.inventory import v200_pb2 as proto_dot_inventory_dot_v200__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/inventory/v200_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InventoryServiceStub(object):
    """InventoryService provides methods for retrieving inventory information
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInventoryLevels = channel.unary_unary(
                '/inventory.InventoryService/GetInventoryLevels',
                request_serializer=proto_dot_inventory_dot_v200__pb2.GetInventoryLevelsRequest.SerializeToString,
                response_deserializer=proto_dot_inventory_dot_v200__pb2.GetInventoryLevelsResponse.FromString,
                _registered_method=True)
        self.GetFilterValues = channel.unary_unary(
                '/inventory.InventoryService/GetFilterValues',
                request_serializer=proto_dot_inventory_dot_v200__pb2.GetFilterValuesRequest.SerializeToString,
                response_deserializer=proto_dot_inventory_dot_v200__pb2.GetFilterValuesResponse.FromString,
                _registered_method=True)
        self.GetInventoryLevelsV121 = channel.unary_unary(
                '/inventory.InventoryService/GetInventoryLevelsV121',
                request_serializer=proto_dot_inventory_dot_v121__pb2.GetInventoryLevelsRequestV121.SerializeToString,
                response_deserializer=proto_dot_inventory_dot_v121__pb2.GetInventoryLevelsResponseV121.FromString,
                _registered_method=True)
        self.GetFilterValuesV121 = channel.unary_unary(
                '/inventory.InventoryService/GetFilterValuesV121',
                request_serializer=proto_dot_inventory_dot_v121__pb2.GetFilterValuesRequestV121.SerializeToString,
                response_deserializer=proto_dot_inventory_dot_v121__pb2.GetFilterValuesResponseV121.FromString,
                _registered_method=True)


class InventoryServiceServicer(object):
    """InventoryService provides methods for retrieving inventory information
    """

    def GetInventoryLevels(self, request, context):
        """GetInventoryLevels retrieves inventory levels for a product (v2.0.0)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFilterValues(self, request, context):
        """GetFilterValues retrieves available filter values for a product (v2.0.0)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInventoryLevelsV121(self, request, context):
        """GetInventoryLevelsV121 retrieves inventory levels using v1.2.1 API
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFilterValuesV121(self, request, context):
        """GetFilterValuesV121 retrieves available filter values using v1.2.1 API
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInventoryLevels': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInventoryLevels,
                    request_deserializer=proto_dot_inventory_dot_v200__pb2.GetInventoryLevelsRequest.FromString,
                    response_serializer=proto_dot_inventory_dot_v200__pb2.GetInventoryLevelsResponse.SerializeToString,
            ),
            'GetFilterValues': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFilterValues,
                    request_deserializer=proto_dot_inventory_dot_v200__pb2.GetFilterValuesRequest.FromString,
                    response_serializer=proto_dot_inventory_dot_v200__pb2.GetFilterValuesResponse.SerializeToString,
            ),
            'GetInventoryLevelsV121': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInventoryLevelsV121,
                    request_deserializer=proto_dot_inventory_dot_v121__pb2.GetInventoryLevelsRequestV121.FromString,
                    response_serializer=proto_dot_inventory_dot_v121__pb2.GetInventoryLevelsResponseV121.SerializeToString,
            ),
            'GetFilterValuesV121': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFilterValuesV121,
                    request_deserializer=proto_dot_inventory_dot_v121__pb2.GetFilterValuesRequestV121.FromString,
                    response_serializer=proto_dot_inventory_dot_v121__pb2.GetFilterValuesResponseV121.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventory.InventoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inventory.InventoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InventoryService(object):
    """InventoryService provides methods for retrieving inventory information
    """

    @staticmethod
    def GetInventoryLevels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/GetInventoryLevels',
            proto_dot_inventory_dot_v200__pb2.GetInventoryLevelsRequest.SerializeToString,
            proto_dot_inventory_dot_v200__pb2.GetInventoryLevelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFilterValues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/GetFilterValues',
            proto_dot_inventory_dot_v200__pb2.GetFilterValuesRequest.SerializeToString,
            proto_dot_inventory_dot_v200__pb2.GetFilterValuesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInventoryLevelsV121(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/GetInventoryLevelsV121',
            proto_dot_inventory_dot_v121__pb2.GetInventoryLevelsRequestV121.SerializeToString,
            proto_dot_inventory_dot_v121__pb2.GetInventoryLevelsResponseV121.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFilterValuesV121(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/GetFilterValuesV121',
            proto_dot_inventory_dot_v121__pb2.GetFilterValuesRequestV121.SerializeToString,
            proto_dot_inventory_dot_v121__pb2.GetFilterValuesResponseV121.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
