# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.ppc import v100_pb2 as proto_dot_ppc_dot_v100__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/ppc/v100_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PPCServiceStub(object):
    """PPCService provides methods for Product Pricing and Configuration data
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAvailableLocations = channel.unary_unary(
                '/ppc.PPCService/GetAvailableLocations',
                request_serializer=proto_dot_ppc_dot_v100__pb2.GetAvailableLocationsRequest.SerializeToString,
                response_deserializer=proto_dot_ppc_dot_v100__pb2.GetAvailableLocationsResponse.FromString,
                _registered_method=True)
        self.GetDecorationColors = channel.unary_unary(
                '/ppc.PPCService/GetDecorationColors',
                request_serializer=proto_dot_ppc_dot_v100__pb2.GetDecorationColorsRequest.SerializeToString,
                response_deserializer=proto_dot_ppc_dot_v100__pb2.GetDecorationColorsResponse.FromString,
                _registered_method=True)
        self.GetFobPoints = channel.unary_unary(
                '/ppc.PPCService/GetFobPoints',
                request_serializer=proto_dot_ppc_dot_v100__pb2.GetFobPointsRequest.SerializeToString,
                response_deserializer=proto_dot_ppc_dot_v100__pb2.GetFobPointsResponse.FromString,
                _registered_method=True)
        self.GetAvailableCharges = channel.unary_unary(
                '/ppc.PPCService/GetAvailableCharges',
                request_serializer=proto_dot_ppc_dot_v100__pb2.GetAvailableChargesRequest.SerializeToString,
                response_deserializer=proto_dot_ppc_dot_v100__pb2.GetAvailableChargesResponse.FromString,
                _registered_method=True)
        self.GetConfigurationAndPricing = channel.unary_unary(
                '/ppc.PPCService/GetConfigurationAndPricing',
                request_serializer=proto_dot_ppc_dot_v100__pb2.GetConfigurationAndPricingRequest.SerializeToString,
                response_deserializer=proto_dot_ppc_dot_v100__pb2.GetConfigurationAndPricingResponse.FromString,
                _registered_method=True)


class PPCServiceServicer(object):
    """PPCService provides methods for Product Pricing and Configuration data
    """

    def GetAvailableLocations(self, request, context):
        """GetAvailableLocations retrieves available decoration locations for a product
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDecorationColors(self, request, context):
        """GetDecorationColors retrieves available decoration colors for a product at a location
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFobPoints(self, request, context):
        """GetFobPoints retrieves FOB (Free On Board) shipping points
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableCharges(self, request, context):
        """GetAvailableCharges retrieves available charges for products
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfigurationAndPricing(self, request, context):
        """GetConfigurationAndPricing retrieves full configuration and pricing for a product
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PPCServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAvailableLocations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableLocations,
                    request_deserializer=proto_dot_ppc_dot_v100__pb2.GetAvailableLocationsRequest.FromString,
                    response_serializer=proto_dot_ppc_dot_v100__pb2.GetAvailableLocationsResponse.SerializeToString,
            ),
            'GetDecorationColors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDecorationColors,
                    request_deserializer=proto_dot_ppc_dot_v100__pb2.GetDecorationColorsRequest.FromString,
                    response_serializer=proto_dot_ppc_dot_v100__pb2.GetDecorationColorsResponse.SerializeToString,
            ),
            'GetFobPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFobPoints,
                    request_deserializer=proto_dot_ppc_dot_v100__pb2.GetFobPointsRequest.FromString,
                    response_serializer=proto_dot_ppc_dot_v100__pb2.GetFobPointsResponse.SerializeToString,
            ),
            'GetAvailableCharges': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableCharges,
                    request_deserializer=proto_dot_ppc_dot_v100__pb2.GetAvailableChargesRequest.FromString,
                    response_serializer=proto_dot_ppc_dot_v100__pb2.GetAvailableChargesResponse.SerializeToString,
            ),
            'GetConfigurationAndPricing': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfigurationAndPricing,
                    request_deserializer=proto_dot_ppc_dot_v100__pb2.GetConfigurationAndPricingRequest.FromString,
                    response_serializer=proto_dot_ppc_dot_v100__pb2.GetConfigurationAndPricingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ppc.PPCService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ppc.PPCService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PPCService(object):
    """PPCService provides methods for Product Pricing and Configuration data
    """

    @staticmethod
    def GetAvailableLocations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ppc.PPCService/GetAvailableLocations',
            proto_dot_ppc_dot_v100__pb2.GetAvailableLocationsRequest.SerializeToString,
            proto_dot_ppc_dot_v100__pb2.GetAvailableLocationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDecorationColors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ppc.PPCService/GetDecorationColors',
            proto_dot_ppc_dot_v100__pb2.GetDecorationColorsRequest.SerializeToString,
            proto_dot_ppc_dot_v100__pb2.GetDecorationColorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFobPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ppc.PPCService/GetFobPoints',
            proto_dot_ppc_dot_v100__pb2.GetFobPointsRequest.SerializeToString,
            proto_dot_ppc_dot_v100__pb2.GetFobPointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvailableCharges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ppc.PPCService/GetAvailableCharges',
            proto_dot_ppc_dot_v100__pb2.GetAvailableChargesRequest.SerializeToString,
            proto_dot_ppc_dot_v100__pb2.GetAvailableChargesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfigurationAndPricing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ppc.PPCService/GetConfigurationAndPricing',
            proto_dot_ppc_dot_v100__pb2.GetConfigurationAndPricingRequest.SerializeToString,
            proto_dot_ppc_dot_v100__pb2.GetConfigurationAndPricingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
