# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.remittanceadvice import remittanceadvice_pb2 as proto_dot_remittanceadvice_dot_remittanceadvice__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/remittanceadvice/remittanceadvice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RemittanceAdviceServiceStub(object):
    """Remittance Advice Service v1.0.0
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendRemittanceAdvice = channel.unary_unary(
                '/remittanceadvice.RemittanceAdviceService/SendRemittanceAdvice',
                request_serializer=proto_dot_remittanceadvice_dot_remittanceadvice__pb2.SendRemittanceAdviceRequest.SerializeToString,
                response_deserializer=proto_dot_remittanceadvice_dot_remittanceadvice__pb2.SendRemittanceAdviceResponse.FromString,
                _registered_method=True)
        self.GetServiceMethods = channel.unary_unary(
                '/remittanceadvice.RemittanceAdviceService/GetServiceMethods',
                request_serializer=proto_dot_remittanceadvice_dot_remittanceadvice__pb2.GetServiceMethodsRequest.SerializeToString,
                response_deserializer=proto_dot_remittanceadvice_dot_remittanceadvice__pb2.GetServiceMethodsResponse.FromString,
                _registered_method=True)


class RemittanceAdviceServiceServicer(object):
    """Remittance Advice Service v1.0.0
    """

    def SendRemittanceAdvice(self, request, context):
        """Send remittance advice
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceMethods(self, request, context):
        """Get available service methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemittanceAdviceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendRemittanceAdvice': grpc.unary_unary_rpc_method_handler(
                    servicer.SendRemittanceAdvice,
                    request_deserializer=proto_dot_remittanceadvice_dot_remittanceadvice__pb2.SendRemittanceAdviceRequest.FromString,
                    response_serializer=proto_dot_remittanceadvice_dot_remittanceadvice__pb2.SendRemittanceAdviceResponse.SerializeToString,
            ),
            'GetServiceMethods': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceMethods,
                    request_deserializer=proto_dot_remittanceadvice_dot_remittanceadvice__pb2.GetServiceMethodsRequest.FromString,
                    response_serializer=proto_dot_remittanceadvice_dot_remittanceadvice__pb2.GetServiceMethodsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'remittanceadvice.RemittanceAdviceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('remittanceadvice.RemittanceAdviceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RemittanceAdviceService(object):
    """Remittance Advice Service v1.0.0
    """

    @staticmethod
    def SendRemittanceAdvice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remittanceadvice.RemittanceAdviceService/SendRemittanceAdvice',
            proto_dot_remittanceadvice_dot_remittanceadvice__pb2.SendRemittanceAdviceRequest.SerializeToString,
            proto_dot_remittanceadvice_dot_remittanceadvice__pb2.SendRemittanceAdviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServiceMethods(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remittanceadvice.RemittanceAdviceService/GetServiceMethods',
            proto_dot_remittanceadvice_dot_remittanceadvice__pb2.GetServiceMethodsRequest.SerializeToString,
            proto_dot_remittanceadvice_dot_remittanceadvice__pb2.GetServiceMethodsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
