# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/product/fast.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/product/fast.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from psdomain.proto.inventory import shared_pb2 as proto_dot_inventory_dot_shared__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/product/fast.proto\x12\x07product\x1a\x1cproto/inventory/shared.proto\"H\n\x0bSlimProduct\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08variants\x18\x02 \x03(\t\x12\x13\n\x0bno_variants\x18\x03 \x01(\x05\"s\n\x14SellableFastResponse\x12&\n\x08products\x18\x01 \x03(\x0b\x32\x14.product.SlimProduct\x12\x33\n\x10service_messages\x18\x02 \x03(\x0b\x32\x19.inventory.ServiceMessage\"f\n\x1aSellableProductIdsResponse\x12\x13\n\x0bproduct_ids\x18\x01 \x03(\t\x12\x33\n\x10service_messages\x18\x02 \x03(\x0b\x32\x19.inventory.ServiceMessageB%Z#promostandardsgateway/proto/productb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.product.fast_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#promostandardsgateway/proto/product'
  _globals['_SLIMPRODUCT']._serialized_start=67
  _globals['_SLIMPRODUCT']._serialized_end=139
  _globals['_SELLABLEFASTRESPONSE']._serialized_start=141
  _globals['_SELLABLEFASTRESPONSE']._serialized_end=256
  _globals['_SELLABLEPRODUCTIDSRESPONSE']._serialized_start=258
  _globals['_SELLABLEPRODUCTIDSRESPONSE']._serialized_end=360
# @@protoc_insertion_point(module_scope)
