# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from psdomain.proto.product import v100_pb2 as proto_dot_product_dot_v100__pb2
from psdomain.proto.product import v200_pb2 as proto_dot_product_dot_v200__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/product/v200_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductServiceStub(object):
    """ProductService provides methods for retrieving product data
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProduct = channel.unary_unary(
                '/product.ProductService/GetProduct',
                request_serializer=proto_dot_product_dot_v200__pb2.GetProductRequest.SerializeToString,
                response_deserializer=proto_dot_product_dot_v200__pb2.GetProductResponse.FromString,
                _registered_method=True)
        self.GetProductCloseOut = channel.unary_unary(
                '/product.ProductService/GetProductCloseOut',
                request_serializer=proto_dot_product_dot_v200__pb2.GetProductCloseOutRequest.SerializeToString,
                response_deserializer=proto_dot_product_dot_v200__pb2.GetProductCloseOutResponse.FromString,
                _registered_method=True)
        self.GetProductSellable = channel.unary_unary(
                '/product.ProductService/GetProductSellable',
                request_serializer=proto_dot_product_dot_v200__pb2.GetProductSellableRequest.SerializeToString,
                response_deserializer=proto_dot_product_dot_v200__pb2.GetProductSellableResponse.FromString,
                _registered_method=True)
        self.GetProductDateModified = channel.unary_unary(
                '/product.ProductService/GetProductDateModified',
                request_serializer=proto_dot_product_dot_v200__pb2.GetProductDateModifiedRequest.SerializeToString,
                response_deserializer=proto_dot_product_dot_v200__pb2.GetProductDateModifiedResponse.FromString,
                _registered_method=True)
        self.GetProductV100 = channel.unary_unary(
                '/product.ProductService/GetProductV100',
                request_serializer=proto_dot_product_dot_v100__pb2.GetProductRequestV100.SerializeToString,
                response_deserializer=proto_dot_product_dot_v100__pb2.GetProductResponseV100.FromString,
                _registered_method=True)
        self.GetProductCloseOutV100 = channel.unary_unary(
                '/product.ProductService/GetProductCloseOutV100',
                request_serializer=proto_dot_product_dot_v100__pb2.GetProductCloseOutRequestV100.SerializeToString,
                response_deserializer=proto_dot_product_dot_v100__pb2.GetProductCloseOutResponseV100.FromString,
                _registered_method=True)
        self.GetProductSellableV100 = channel.unary_unary(
                '/product.ProductService/GetProductSellableV100',
                request_serializer=proto_dot_product_dot_v100__pb2.GetProductSellableRequestV100.SerializeToString,
                response_deserializer=proto_dot_product_dot_v100__pb2.GetProductSellableResponseV100.FromString,
                _registered_method=True)
        self.GetProductDateModifiedV100 = channel.unary_unary(
                '/product.ProductService/GetProductDateModifiedV100',
                request_serializer=proto_dot_product_dot_v100__pb2.GetProductDateModifiedRequestV100.SerializeToString,
                response_deserializer=proto_dot_product_dot_v100__pb2.GetProductDateModifiedResponseV100.FromString,
                _registered_method=True)


class ProductServiceServicer(object):
    """ProductService provides methods for retrieving product data
    """

    def GetProduct(self, request, context):
        """v2.0.0 methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProductCloseOut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProductSellable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProductDateModified(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProductV100(self, request, context):
        """v1.0.0 methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProductCloseOutV100(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProductSellableV100(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProductDateModifiedV100(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProduct,
                    request_deserializer=proto_dot_product_dot_v200__pb2.GetProductRequest.FromString,
                    response_serializer=proto_dot_product_dot_v200__pb2.GetProductResponse.SerializeToString,
            ),
            'GetProductCloseOut': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductCloseOut,
                    request_deserializer=proto_dot_product_dot_v200__pb2.GetProductCloseOutRequest.FromString,
                    response_serializer=proto_dot_product_dot_v200__pb2.GetProductCloseOutResponse.SerializeToString,
            ),
            'GetProductSellable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductSellable,
                    request_deserializer=proto_dot_product_dot_v200__pb2.GetProductSellableRequest.FromString,
                    response_serializer=proto_dot_product_dot_v200__pb2.GetProductSellableResponse.SerializeToString,
            ),
            'GetProductDateModified': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductDateModified,
                    request_deserializer=proto_dot_product_dot_v200__pb2.GetProductDateModifiedRequest.FromString,
                    response_serializer=proto_dot_product_dot_v200__pb2.GetProductDateModifiedResponse.SerializeToString,
            ),
            'GetProductV100': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductV100,
                    request_deserializer=proto_dot_product_dot_v100__pb2.GetProductRequestV100.FromString,
                    response_serializer=proto_dot_product_dot_v100__pb2.GetProductResponseV100.SerializeToString,
            ),
            'GetProductCloseOutV100': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductCloseOutV100,
                    request_deserializer=proto_dot_product_dot_v100__pb2.GetProductCloseOutRequestV100.FromString,
                    response_serializer=proto_dot_product_dot_v100__pb2.GetProductCloseOutResponseV100.SerializeToString,
            ),
            'GetProductSellableV100': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductSellableV100,
                    request_deserializer=proto_dot_product_dot_v100__pb2.GetProductSellableRequestV100.FromString,
                    response_serializer=proto_dot_product_dot_v100__pb2.GetProductSellableResponseV100.SerializeToString,
            ),
            'GetProductDateModifiedV100': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductDateModifiedV100,
                    request_deserializer=proto_dot_product_dot_v100__pb2.GetProductDateModifiedRequestV100.FromString,
                    response_serializer=proto_dot_product_dot_v100__pb2.GetProductDateModifiedResponseV100.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'product.ProductService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('product.ProductService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductService(object):
    """ProductService provides methods for retrieving product data
    """

    @staticmethod
    def GetProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/GetProduct',
            proto_dot_product_dot_v200__pb2.GetProductRequest.SerializeToString,
            proto_dot_product_dot_v200__pb2.GetProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProductCloseOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/GetProductCloseOut',
            proto_dot_product_dot_v200__pb2.GetProductCloseOutRequest.SerializeToString,
            proto_dot_product_dot_v200__pb2.GetProductCloseOutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProductSellable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/GetProductSellable',
            proto_dot_product_dot_v200__pb2.GetProductSellableRequest.SerializeToString,
            proto_dot_product_dot_v200__pb2.GetProductSellableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProductDateModified(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/GetProductDateModified',
            proto_dot_product_dot_v200__pb2.GetProductDateModifiedRequest.SerializeToString,
            proto_dot_product_dot_v200__pb2.GetProductDateModifiedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProductV100(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/GetProductV100',
            proto_dot_product_dot_v100__pb2.GetProductRequestV100.SerializeToString,
            proto_dot_product_dot_v100__pb2.GetProductResponseV100.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProductCloseOutV100(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/GetProductCloseOutV100',
            proto_dot_product_dot_v100__pb2.GetProductCloseOutRequestV100.SerializeToString,
            proto_dot_product_dot_v100__pb2.GetProductCloseOutResponseV100.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProductSellableV100(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/GetProductSellableV100',
            proto_dot_product_dot_v100__pb2.GetProductSellableRequestV100.SerializeToString,
            proto_dot_product_dot_v100__pb2.GetProductSellableResponseV100.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProductDateModifiedV100(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/GetProductDateModifiedV100',
            proto_dot_product_dot_v100__pb2.GetProductDateModifiedRequestV100.SerializeToString,
            proto_dot_product_dot_v100__pb2.GetProductDateModifiedResponseV100.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
