# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.media import v110_pb2 as proto_dot_media_dot_v110__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/media/v110_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MediaServiceStub(object):
    """MediaService provides methods for retrieving media content data
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMediaContent = channel.unary_unary(
                '/media.MediaService/GetMediaContent',
                request_serializer=proto_dot_media_dot_v110__pb2.GetMediaContentRequest.SerializeToString,
                response_deserializer=proto_dot_media_dot_v110__pb2.GetMediaContentResponse.FromString,
                _registered_method=True)
        self.GetMediaDateModified = channel.unary_unary(
                '/media.MediaService/GetMediaDateModified',
                request_serializer=proto_dot_media_dot_v110__pb2.GetMediaDateModifiedRequest.SerializeToString,
                response_deserializer=proto_dot_media_dot_v110__pb2.GetMediaDateModifiedResponse.FromString,
                _registered_method=True)


class MediaServiceServicer(object):
    """MediaService provides methods for retrieving media content data
    """

    def GetMediaContent(self, request, context):
        """GetMediaContent retrieves media content for a product
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMediaDateModified(self, request, context):
        """GetMediaDateModified retrieves products/parts with modified media since a timestamp
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MediaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMediaContent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMediaContent,
                    request_deserializer=proto_dot_media_dot_v110__pb2.GetMediaContentRequest.FromString,
                    response_serializer=proto_dot_media_dot_v110__pb2.GetMediaContentResponse.SerializeToString,
            ),
            'GetMediaDateModified': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMediaDateModified,
                    request_deserializer=proto_dot_media_dot_v110__pb2.GetMediaDateModifiedRequest.FromString,
                    response_serializer=proto_dot_media_dot_v110__pb2.GetMediaDateModifiedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'media.MediaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('media.MediaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MediaService(object):
    """MediaService provides methods for retrieving media content data
    """

    @staticmethod
    def GetMediaContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/media.MediaService/GetMediaContent',
            proto_dot_media_dot_v110__pb2.GetMediaContentRequest.SerializeToString,
            proto_dot_media_dot_v110__pb2.GetMediaContentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMediaDateModified(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/media.MediaService/GetMediaDateModified',
            proto_dot_media_dot_v110__pb2.GetMediaDateModifiedRequest.SerializeToString,
            proto_dot_media_dot_v110__pb2.GetMediaDateModifiedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
