# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from psdomain.proto.osn import osn_pb2 as proto_dot_osn_dot_osn__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/osn/osn_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrderShipmentNotificationServiceStub(object):
    """OrderShipmentNotificationService provides methods for Order Shipment Notification data (v1.0.0, v2.0.0, v2.1.0)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOrderShipmentNotificationV100 = channel.unary_unary(
                '/osn.OrderShipmentNotificationService/GetOrderShipmentNotificationV100',
                request_serializer=proto_dot_osn_dot_osn__pb2.GetOrderShipmentNotificationRequestV100.SerializeToString,
                response_deserializer=proto_dot_osn_dot_osn__pb2.GetOrderShipmentNotificationResponseV100.FromString,
                _registered_method=True)
        self.GetOrderShipmentNotificationV200 = channel.unary_unary(
                '/osn.OrderShipmentNotificationService/GetOrderShipmentNotificationV200',
                request_serializer=proto_dot_osn_dot_osn__pb2.GetOrderShipmentNotificationRequestV200.SerializeToString,
                response_deserializer=proto_dot_osn_dot_osn__pb2.GetOrderShipmentNotificationResponseV200.FromString,
                _registered_method=True)
        self.GetOrderShipmentNotificationV210 = channel.unary_unary(
                '/osn.OrderShipmentNotificationService/GetOrderShipmentNotificationV210',
                request_serializer=proto_dot_osn_dot_osn__pb2.GetOrderShipmentNotificationRequestV210.SerializeToString,
                response_deserializer=proto_dot_osn_dot_osn__pb2.GetOrderShipmentNotificationResponseV210.FromString,
                _registered_method=True)
        self.GetServiceMethods = channel.unary_unary(
                '/osn.OrderShipmentNotificationService/GetServiceMethods',
                request_serializer=proto_dot_osn_dot_osn__pb2.GetServiceMethodsRequest.SerializeToString,
                response_deserializer=proto_dot_osn_dot_osn__pb2.GetServiceMethodsResponse.FromString,
                _registered_method=True)
        self.SendAdvanceShipmentNotification = channel.unary_unary(
                '/osn.OrderShipmentNotificationService/SendAdvanceShipmentNotification',
                request_serializer=proto_dot_osn_dot_osn__pb2.SendAdvanceShipmentNotificationRequest.SerializeToString,
                response_deserializer=proto_dot_osn_dot_osn__pb2.SendAdvanceShipmentNotificationResponse.FromString,
                _registered_method=True)


class OrderShipmentNotificationServiceServicer(object):
    """OrderShipmentNotificationService provides methods for Order Shipment Notification data (v1.0.0, v2.0.0, v2.1.0)
    """

    def GetOrderShipmentNotificationV100(self, request, context):
        """v1.0.0 Method
        GetOrderShipmentNotificationV100 retrieves shipment notifications (v1.0.0)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderShipmentNotificationV200(self, request, context):
        """v2.0.0 Method
        GetOrderShipmentNotificationV200 retrieves shipment notifications (v2.0.0)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderShipmentNotificationV210(self, request, context):
        """v2.1.0 Methods
        GetOrderShipmentNotificationV210 retrieves shipment notifications (v2.1.0)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceMethods(self, request, context):
        """GetServiceMethods retrieves the list of supported service methods (v2.1.0)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendAdvanceShipmentNotification(self, request, context):
        """SendAdvanceShipmentNotification sends an ASN to a supplier (v2.1.0)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderShipmentNotificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOrderShipmentNotificationV100': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderShipmentNotificationV100,
                    request_deserializer=proto_dot_osn_dot_osn__pb2.GetOrderShipmentNotificationRequestV100.FromString,
                    response_serializer=proto_dot_osn_dot_osn__pb2.GetOrderShipmentNotificationResponseV100.SerializeToString,
            ),
            'GetOrderShipmentNotificationV200': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderShipmentNotificationV200,
                    request_deserializer=proto_dot_osn_dot_osn__pb2.GetOrderShipmentNotificationRequestV200.FromString,
                    response_serializer=proto_dot_osn_dot_osn__pb2.GetOrderShipmentNotificationResponseV200.SerializeToString,
            ),
            'GetOrderShipmentNotificationV210': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderShipmentNotificationV210,
                    request_deserializer=proto_dot_osn_dot_osn__pb2.GetOrderShipmentNotificationRequestV210.FromString,
                    response_serializer=proto_dot_osn_dot_osn__pb2.GetOrderShipmentNotificationResponseV210.SerializeToString,
            ),
            'GetServiceMethods': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceMethods,
                    request_deserializer=proto_dot_osn_dot_osn__pb2.GetServiceMethodsRequest.FromString,
                    response_serializer=proto_dot_osn_dot_osn__pb2.GetServiceMethodsResponse.SerializeToString,
            ),
            'SendAdvanceShipmentNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAdvanceShipmentNotification,
                    request_deserializer=proto_dot_osn_dot_osn__pb2.SendAdvanceShipmentNotificationRequest.FromString,
                    response_serializer=proto_dot_osn_dot_osn__pb2.SendAdvanceShipmentNotificationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'osn.OrderShipmentNotificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('osn.OrderShipmentNotificationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderShipmentNotificationService(object):
    """OrderShipmentNotificationService provides methods for Order Shipment Notification data (v1.0.0, v2.0.0, v2.1.0)
    """

    @staticmethod
    def GetOrderShipmentNotificationV100(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/osn.OrderShipmentNotificationService/GetOrderShipmentNotificationV100',
            proto_dot_osn_dot_osn__pb2.GetOrderShipmentNotificationRequestV100.SerializeToString,
            proto_dot_osn_dot_osn__pb2.GetOrderShipmentNotificationResponseV100.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrderShipmentNotificationV200(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/osn.OrderShipmentNotificationService/GetOrderShipmentNotificationV200',
            proto_dot_osn_dot_osn__pb2.GetOrderShipmentNotificationRequestV200.SerializeToString,
            proto_dot_osn_dot_osn__pb2.GetOrderShipmentNotificationResponseV200.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrderShipmentNotificationV210(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/osn.OrderShipmentNotificationService/GetOrderShipmentNotificationV210',
            proto_dot_osn_dot_osn__pb2.GetOrderShipmentNotificationRequestV210.SerializeToString,
            proto_dot_osn_dot_osn__pb2.GetOrderShipmentNotificationResponseV210.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServiceMethods(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/osn.OrderShipmentNotificationService/GetServiceMethods',
            proto_dot_osn_dot_osn__pb2.GetServiceMethodsRequest.SerializeToString,
            proto_dot_osn_dot_osn__pb2.GetServiceMethodsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendAdvanceShipmentNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/osn.OrderShipmentNotificationService/SendAdvanceShipmentNotification',
            proto_dot_osn_dot_osn__pb2.SendAdvanceShipmentNotificationRequest.SerializeToString,
            proto_dot_osn_dot_osn__pb2.SendAdvanceShipmentNotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
